#!/bin/bash
cp implementation/system.bit ../bit_files/darkquad29_wvl_2018_Apr_21_1621.bit
./mkbof_64 -o implementation/system.bof -s core_info.tab -t 3 implementation/system.bin
cp implementation/system.bof ../bit_files/darkquad29_wvl_2018_Apr_21_1621.bof
cp design_info.tab ../bit_files/darkquad29_wvl_2018_Apr_21_1621.info
gzip -c ../bit_files/darkquad29_wvl_2018_Apr_21_1621.bof  > ../bit_files/darkquad29_wvl_2018_Apr_21_1621.bof.gz
gzip -c implementation/system.bin > implementation/system.bin.gz
cat implementation/system.bin.gz >> /Scratch/firmware/chan1024/darkquad29_wvl/XPS_ROACH2_base/extended_info.kcpfpg
cp extended_info.kcpfpg ../bit_files/darkquad29_wvl_2018_Apr_21_1621.fpg
