#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/Scratch/firmware/chan1024/darkquad29_wvl/XPS_ROACH2_base/system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /opt/Xilinx/14.3/ISE_DS/EDK

SYSTEM = system

MHSFILE = system.mhs

FPGA_ARCH = virtex6

DEVICE = xc6vsx475tff1759-1

INTSTYLE = default

XPS_HDL_LANG = vhdl
GLOBAL_SEARCHPATHOPT = 
PROJECT_SEARCHPATHOPT = 

SEARCHPATHOPT = $(PROJECT_SEARCHPATHOPT) $(GLOBAL_SEARCHPATHOPT)

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst

OBSERVE_PAR_OPTIONS = -error yes

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
MICROBLAZE_BOOTLOOP_LE = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop_le.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

BRAMINIT_ELF_IMP_FILES =
BRAMINIT_ELF_IMP_FILE_ARGS =

BRAMINIT_ELF_SIM_FILES =
BRAMINIT_ELF_SIM_FILE_ARGS =

SIM_CMD = xterm -e ./isim_system

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.tcl

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.tcl

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.tcl

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_SIM_FILE_ARGS) -msg __xps/ise/xmsgprops.lst -s isim


CORE_STATE_DEVELOPMENT_FILES = pcores/temac_v1_00_a/netlist/emac_wrapper.ngc \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/qdr_controller_v1_00_a/netlist/chipscope_ila.ngc \
pcores/qdr_controller_v1_00_a/netlist/chipscope_icon.ngc \
pcores/opb_qdr_sniffer_v1_00_a/netlist/chipscope_ila.ngc \
pcores/opb_qdr_sniffer_v1_00_a/netlist/chipscope_icon.ngc \
pcores/qdr_controller_v1_00_a/netlist/chipscope_ila.ngc \
pcores/qdr_controller_v1_00_a/netlist/chipscope_icon.ngc \
pcores/opb_qdr_sniffer_v1_00_a/netlist/chipscope_ila.ngc \
pcores/opb_qdr_sniffer_v1_00_a/netlist/chipscope_icon.ngc \
pcores/qdr_controller_v1_00_a/netlist/chipscope_ila.ngc \
pcores/qdr_controller_v1_00_a/netlist/chipscope_icon.ngc \
pcores/opb_qdr_sniffer_v1_00_a/netlist/chipscope_ila.ngc \
pcores/opb_qdr_sniffer_v1_00_a/netlist/chipscope_icon.ngc \
pcores/qdr_controller_v1_00_a/netlist/chipscope_ila.ngc \
pcores/qdr_controller_v1_00_a/netlist/chipscope_icon.ngc \
pcores/opb_qdr_sniffer_v1_00_a/netlist/chipscope_ila.ngc \
pcores/opb_qdr_sniffer_v1_00_a/netlist/chipscope_icon.ngc \
pcores/gbe_udp_v1_00_a/netlist/gbe_arp_cache.ngc \
pcores/gbe_udp_v1_00_a/netlist/gbe_cpu_buffer.ngc \
pcores/gbe_udp_v1_00_a/netlist/gbe_ctrl_fifo.ngc \
pcores/gbe_udp_v1_00_a/netlist/gbe_rx_ctrl_fifo.ngc \
pcores/gbe_udp_v1_00_a/netlist/gbe_rx_packet_fifo.ngc \
pcores/gbe_udp_v1_00_a/netlist/gbe_tx_packet_fifo.ngc \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/temac_v1_00_a/hdl/verilog/temac.v \
pcores/temac_v1_00_a/hdl/verilog/emac_wrapper.v \
pcores/sgmii_phy_v1_00_a/hdl/verilog/sgmii_gtx.v \
pcores/sgmii_phy_v1_00_a/hdl/verilog/sgmii_phy.v \
pcores/roach_infrastructure_v1_00_a/hdl/verilog/roach_infrastructure.v \
pcores/reset_block_v1_00_a/hdl/verilog/reset_block.v \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_utils_v1_00_a/hdl/vhdl/conv_funs_pkg.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/family.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/coregen_comp_defs.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/common_types_pkg.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/proc_common_pkg.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/conv_funs_pkg.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/ipif_pkg.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/addsub.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/counter_bit.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/counter.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/direct_path_cntr.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/direct_path_cntr_ai.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/down_counter.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/eval_timer.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/inferred_lut4.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/ipif_steer.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/ld_arith_reg.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/ld_arith_reg2.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/mux_onehot.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/or_bits.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/or_muxcy.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/or_gate.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/pf_adder_bit.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/pf_adder.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/pf_counter_bit.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/pf_counter.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/pf_counter_top.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/pf_occ_counter.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/pf_occ_counter_top.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/pf_dpram_select.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/pselect.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/pselect_mask.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/srl16_fifo.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/srl_fifo.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/srl_fifo2.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/srl_fifo_rbu.vhd \
pcores/proc_common_v2_00_a/hdl/vhdl/valid_be.vhd \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/interrupt_control_v1_00_a/hdl/vhdl/interrupt_control.vhd \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/wrpfifo_v1_01_b/hdl/vhdl/pf_dly1_mux.vhd \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/wrpfifo_v1_01_b/hdl/vhdl/wrpfifo_dp_cntl.vhd \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/wrpfifo_v1_01_b/hdl/vhdl/ipif_control_wr.vhd \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/wrpfifo_v1_01_b/hdl/vhdl/wrpfifo_top.vhd \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/rdpfifo_v1_01_b/hdl/vhdl/rdpfifo_dp_cntl.vhd \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/rdpfifo_v1_01_b/hdl/vhdl/ipif_control_rd.vhd \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/rdpfifo_v1_01_b/hdl/vhdl/rdpfifo_top.vhd \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/reset_mir.vhd \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/brst_addr_cntr.vhd \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/opb_flex_addr_cntr.vhd \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/brst_addr_cntr_reg.vhd \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/opb_be_gen.vhd \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/srl_fifo3.vhd \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/write_buffer.vhd \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/opb_bam.vhd \
/opt/Xilinx/14.3/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/opb_ipif_v3_01_a/hdl/vhdl/opb_ipif.vhd \
pcores/opb_arbiter_v1_02_e/hdl/vhdl/opb_arb_pkg.vhd \
pcores/opb_arbiter_v1_02_e/hdl/vhdl/or_muxcy.vhd \
pcores/opb_arbiter_v1_02_e/hdl/vhdl/mux_onehot.vhd \
pcores/opb_arbiter_v1_02_e/hdl/vhdl/or_bits.vhd \
pcores/opb_arbiter_v1_02_e/hdl/vhdl/or_gate.vhd \
pcores/opb_arbiter_v1_02_e/hdl/vhdl/priority_reg.vhd \
pcores/opb_arbiter_v1_02_e/hdl/vhdl/onehot2encoded.vhd \
pcores/opb_arbiter_v1_02_e/hdl/vhdl/arbitration_logic.vhd \
pcores/opb_arbiter_v1_02_e/hdl/vhdl/park_lock_logic.vhd \
pcores/opb_arbiter_v1_02_e/hdl/vhdl/watchdog_timer.vhd \
pcores/opb_arbiter_v1_02_e/hdl/vhdl/arb2bus_data_mux.vhd \
pcores/opb_arbiter_v1_02_e/hdl/vhdl/control_register_logic.vhd \
pcores/opb_arbiter_v1_02_e/hdl/vhdl/ipif_regonly_slave.vhd \
pcores/opb_arbiter_v1_02_e/hdl/vhdl/priority_register_logic.vhd \
pcores/opb_arbiter_v1_02_e/hdl/vhdl/opb_arbiter_core.vhd \
pcores/opb_arbiter_v1_02_e/hdl/vhdl/opb_arbiter.vhd \
pcores/opb_v20_v1_10_c/hdl/vhdl/opb_v20.vhd \
pcores/epb32_opb_bridge_v1_00_a/hdl/verilog/epb32_opb_bridge.v \
pcores/epb_infrastructure_v1_00_a/hdl/verilog/epb_infrastructure.v \
pcores/sys_block_v1_00_a/hdl/verilog/sys_block.v \
pcores/opb_register_ppc2simulink_v1_00_a/hdl/verilog/opb_register_ppc2simulink.v \
pcores/opb_register_simulink2ppc_v1_00_a/hdl/verilog/opb_register_simulink2ppc.v \
pcores/bram_block_custom_v1_00_a/hdl/verilog/bram_block_custom.v \
pcores/bram_block_custom_v1_00_a/hdl/verilog/bram.v \
pcores/qdr_controller_v1_00_a/hdl/verilog/qdr_controller.v \
pcores/qdr_controller_v1_00_a/hdl/verilog/qdrc_infrastructure.v \
pcores/qdr_controller_v1_00_a/hdl/verilog/qdrc_rd.v \
pcores/qdr_controller_v1_00_a/hdl/verilog/qdrc_wr.v \
pcores/qdr_controller_v1_00_a/hdl/verilog/rt_var_delay.v \
pcores/qdr_controller_v1_00_a/hdl/verilog/chipscope_icon.v \
pcores/qdr_controller_v1_00_a/hdl/verilog/chipscope_ila.v \
pcores/opb_qdr_sniffer_v1_00_a/hdl/verilog/opb_qdr_sniffer.v \
pcores/opb_qdr_sniffer_v1_00_a/hdl/verilog/async_qdr_interface.v \
pcores/opb_qdr_sniffer_v1_00_a/hdl/verilog/async_qdr_interface36.v \
pcores/opb_qdr_sniffer_v1_00_a/hdl/verilog/qdr_config.v \
pcores/opb_qdr_sniffer_v1_00_a/hdl/verilog/edge_detect.v \
pcores/opb_qdr_sniffer_v1_00_a/hdl/verilog/clk_domain_crosser.v \
pcores/opb_qdr_sniffer_v1_00_a/hdl/verilog/chipscope_ila.v \
pcores/opb_qdr_sniffer_v1_00_a/hdl/verilog/chipscope_icon.v \
pcores/gbe_udp_v1_00_a/hdl/verilog/gbe_arp_cache.v \
pcores/gbe_udp_v1_00_a/hdl/verilog/gbe_cpu_buffer.v \
pcores/gbe_udp_v1_00_a/hdl/verilog/gbe_ctrl_fifo.v \
pcores/gbe_udp_v1_00_a/hdl/verilog/gbe_cpu_attach.v \
pcores/gbe_udp_v1_00_a/hdl/verilog/gbe_rx_ctrl_fifo.v \
pcores/gbe_udp_v1_00_a/hdl/verilog/gbe_rx_packet_fifo.v \
pcores/gbe_udp_v1_00_a/hdl/verilog/gbe_rx.v \
pcores/gbe_udp_v1_00_a/hdl/verilog/gbe_tx.v \
pcores/gbe_udp_v1_00_a/hdl/verilog/gbe_udp.v \
pcores/gbe_udp_v1_00_a/hdl/verilog/gbe_tx_packet_fifo.v

WRAPPER_NGC_FILES = implementation/system_temac_inst_wrapper.ngc \
implementation/system_sgmii_phy_inst_wrapper.ngc \
implementation/system_infrastructure_inst_wrapper.ngc \
implementation/system_reset_block_inst_wrapper.ngc \
implementation/system_opb0_wrapper.ngc \
implementation/system_epb_opb_bridge_inst_wrapper.ngc \
implementation/system_epb_infrastructure_inst_wrapper.ngc \
implementation/system_sys_block_inst_wrapper.ngc \
implementation/system_darkquad29_wvl_a2g_ctrl_adcdac_2g_ctrl_wrapper.ngc \
implementation/system_darkquad29_wvl_a2g_ctrl_en_bram_dump_wrapper.ngc \
implementation/system_darkquad29_wvl_a2g_ctrl_in_val_wrapper.ngc \
implementation/system_darkquad29_wvl_a2g_ctrl_last_tx_data_wrapper.ngc \
implementation/system_darkquad29_wvl_a2g_ctrl_lut_dump_buffer_size_wrapper.ngc \
implementation/system_darkquad29_wvl_a2g_ctrl_lut_dump_dac_lut_buffer_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_a2g_ctrl_lut_dump_dac_lut_buffer_wrapper.ngc \
implementation/system_darkquad29_wvl_a2g_ctrl_lut_dump_data_period_wrapper.ngc \
implementation/system_darkquad29_wvl_a2g_ctrl_lut_dump_sending_data_wrapper.ngc \
implementation/system_darkquad29_wvl_a2g_ctrl_reg_rx_full_wrapper.ngc \
implementation/system_darkquad29_wvl_a2g_ctrl_reg_tx_full_wrapper.ngc \
implementation/system_darkquad29_wvl_a2g_ctrl_rst_wrapper.ngc \
implementation/system_darkquad29_wvl_a2g_ctrl_tx_en_wrapper.ngc \
implementation/system_darkquad29_wvl_a2g_ctrl_v7_ready_wrapper.ngc \
implementation/system_darkquad29_wvl_acc_iq_avg0_ss_bram_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_acc_iq_avg0_ss_bram_wrapper.ngc \
implementation/system_darkquad29_wvl_acc_iq_avg0_ss_ctrl_wrapper.ngc \
implementation/system_darkquad29_wvl_acc_iq_avg0_ss_status_wrapper.ngc \
implementation/system_darkquad29_wvl_acc_iq_avg1_ss_bram_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_acc_iq_avg1_ss_bram_wrapper.ngc \
implementation/system_darkquad29_wvl_acc_iq_avg1_ss_ctrl_wrapper.ngc \
implementation/system_darkquad29_wvl_acc_iq_avg1_ss_status_wrapper.ngc \
implementation/system_darkquad29_wvl_acc_iq_avg2_ss_bram_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_acc_iq_avg2_ss_bram_wrapper.ngc \
implementation/system_darkquad29_wvl_acc_iq_avg2_ss_ctrl_wrapper.ngc \
implementation/system_darkquad29_wvl_acc_iq_avg2_ss_status_wrapper.ngc \
implementation/system_darkquad29_wvl_acc_iq_avg3_ss_bram_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_acc_iq_avg3_ss_bram_wrapper.ngc \
implementation/system_darkquad29_wvl_acc_iq_avg3_ss_ctrl_wrapper.ngc \
implementation/system_darkquad29_wvl_acc_iq_avg3_ss_status_wrapper.ngc \
implementation/system_darkquad29_wvl_acc_iq_start_acc_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_adcdac_2g_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_dly_val_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_i_scale_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_inc_phs_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_load_dly_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_locked_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_n_miss_pps_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_pos_phs_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_raw_pps_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_snp_cal0_ss_bram_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_snp_cal0_ss_bram_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_snp_cal0_ss_ctrl_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_snp_cal0_ss_status_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_snp_cal1_ss_bram_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_snp_cal1_ss_bram_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_snp_cal1_ss_ctrl_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_snp_cal1_ss_status_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_snp_cal2_ss_bram_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_snp_cal2_ss_bram_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_snp_cal2_ss_ctrl_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_snp_cal2_ss_status_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_snp_cal3_ss_bram_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_snp_cal3_ss_bram_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_snp_cal3_ss_ctrl_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_snp_cal3_ss_status_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_trig_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_ts0_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_ts1_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_ts2_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_ts3_wrapper.ngc \
implementation/system_darkquad29_wvl_adc_in_valid_wrapper.ngc \
implementation/system_darkquad29_wvl_board_num_wrapper.ngc \
implementation/system_darkquad29_wvl_capture0_base_kf_wrapper.ngc \
implementation/system_darkquad29_wvl_capture0_base_kq_wrapper.ngc \
implementation/system_darkquad29_wvl_capture0_cps_lim_wrapper.ngc \
implementation/system_darkquad29_wvl_capture0_energy_cal_lut_energy_coeffs_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_capture0_energy_cal_lut_energy_coeffs_wrapper.ngc \
implementation/system_darkquad29_wvl_capture0_load_thresh_wrapper.ngc \
implementation/system_darkquad29_wvl_capture0_pix_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_capture0_pix_wrapper.ngc \
implementation/system_darkquad29_wvl_capture0_threshold_wrapper.ngc \
implementation/system_darkquad29_wvl_capture0_use_energy_cal_wrapper.ngc \
implementation/system_darkquad29_wvl_capture1_base_kf_wrapper.ngc \
implementation/system_darkquad29_wvl_capture1_base_kq_wrapper.ngc \
implementation/system_darkquad29_wvl_capture1_cps_lim_wrapper.ngc \
implementation/system_darkquad29_wvl_capture1_energy_cal_lut_energy_coeffs_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_capture1_energy_cal_lut_energy_coeffs_wrapper.ngc \
implementation/system_darkquad29_wvl_capture1_load_thresh_wrapper.ngc \
implementation/system_darkquad29_wvl_capture1_pix_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_capture1_pix_wrapper.ngc \
implementation/system_darkquad29_wvl_capture1_threshold_wrapper.ngc \
implementation/system_darkquad29_wvl_capture1_use_energy_cal_wrapper.ngc \
implementation/system_darkquad29_wvl_capture2_base_kf_wrapper.ngc \
implementation/system_darkquad29_wvl_capture2_base_kq_wrapper.ngc \
implementation/system_darkquad29_wvl_capture2_cps_lim_wrapper.ngc \
implementation/system_darkquad29_wvl_capture2_energy_cal_lut_energy_coeffs_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_capture2_energy_cal_lut_energy_coeffs_wrapper.ngc \
implementation/system_darkquad29_wvl_capture2_load_thresh_wrapper.ngc \
implementation/system_darkquad29_wvl_capture2_pix_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_capture2_pix_wrapper.ngc \
implementation/system_darkquad29_wvl_capture2_threshold_wrapper.ngc \
implementation/system_darkquad29_wvl_capture2_use_energy_cal_wrapper.ngc \
implementation/system_darkquad29_wvl_capture3_base_kf_wrapper.ngc \
implementation/system_darkquad29_wvl_capture3_base_kq_wrapper.ngc \
implementation/system_darkquad29_wvl_capture3_cps_lim_wrapper.ngc \
implementation/system_darkquad29_wvl_capture3_energy_cal_lut_energy_coeffs_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_capture3_energy_cal_lut_energy_coeffs_wrapper.ngc \
implementation/system_darkquad29_wvl_capture3_load_thresh_wrapper.ngc \
implementation/system_darkquad29_wvl_capture3_pix_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_capture3_pix_wrapper.ngc \
implementation/system_darkquad29_wvl_capture3_threshold_wrapper.ngc \
implementation/system_darkquad29_wvl_capture3_use_energy_cal_wrapper.ngc \
implementation/system_darkquad29_wvl_chan_sel_ch_bin0_wrapper.ngc \
implementation/system_darkquad29_wvl_chan_sel_ch_bin1_wrapper.ngc \
implementation/system_darkquad29_wvl_chan_sel_ch_bin2_wrapper.ngc \
implementation/system_darkquad29_wvl_chan_sel_ch_bin3_wrapper.ngc \
implementation/system_darkquad29_wvl_chan_sel_load_wrapper.ngc \
implementation/system_darkquad29_wvl_check_lag_data_ch_wrapper.ngc \
implementation/system_darkquad29_wvl_check_lag_dds_ch_wrapper.ngc \
implementation/system_darkquad29_wvl_check_lag_latch_wrapper.ngc \
implementation/system_darkquad29_wvl_conv_phase0_centers_wrapper.ngc \
implementation/system_darkquad29_wvl_conv_phase0_load_centers_wrapper.ngc \
implementation/system_darkquad29_wvl_conv_phase1_centers_wrapper.ngc \
implementation/system_darkquad29_wvl_conv_phase1_load_centers_wrapper.ngc \
implementation/system_darkquad29_wvl_conv_phase2_centers_wrapper.ngc \
implementation/system_darkquad29_wvl_conv_phase2_load_centers_wrapper.ngc \
implementation/system_darkquad29_wvl_conv_phase3_centers_wrapper.ngc \
implementation/system_darkquad29_wvl_conv_phase3_load_centers_wrapper.ngc \
implementation/system_qdr0_controller_wrapper.ngc \
implementation/system_qdr0_sniffer_wrapper.ngc \
implementation/system_qdr1_controller_wrapper.ngc \
implementation/system_qdr1_sniffer_wrapper.ngc \
implementation/system_qdr2_controller_wrapper.ngc \
implementation/system_qdr2_sniffer_wrapper.ngc \
implementation/system_qdr3_controller_wrapper.ngc \
implementation/system_qdr3_sniffer_wrapper.ngc \
implementation/system_darkquad29_wvl_dds_lut_run_wrapper.ngc \
implementation/system_darkquad29_wvl_dds_shift_wrapper.ngc \
implementation/system_darkquad29_wvl_gbe64_dest_ip_wrapper.ngc \
implementation/system_darkquad29_wvl_gbe64_one_gbe_wrapper.ngc \
implementation/system_darkquad29_wvl_gbe64_rst_wrapper.ngc \
implementation/system_darkquad29_wvl_gbe64_tx_afull_wrapper.ngc \
implementation/system_darkquad29_wvl_gbe64_tx_overrun_wrapper.ngc \
implementation/system_darkquad29_wvl_gbe64_words_per_frame_wrapper.ngc \
implementation/system_darkquad29_wvl_n_eof_sent_wrapper.ngc \
implementation/system_darkquad29_wvl_n_photons_wrapper.ngc \
implementation/system_darkquad29_wvl_pfb_fft_check_fft_oflow_wrapper.ngc \
implementation/system_darkquad29_wvl_phase_dmp_ch_we_wrapper.ngc \
implementation/system_darkquad29_wvl_phase_dmp_on_wrapper.ngc \
implementation/system_darkquad29_wvl_phase_port_wrapper.ngc \
implementation/system_darkquad29_wvl_photon_port_wrapper.ngc \
implementation/system_darkquad29_wvl_prog_fir0_load_chan_wrapper.ngc \
implementation/system_darkquad29_wvl_prog_fir0_single_chan_coeffs_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_prog_fir0_single_chan_coeffs_wrapper.ngc \
implementation/system_darkquad29_wvl_prog_fir1_load_chan_wrapper.ngc \
implementation/system_darkquad29_wvl_prog_fir1_single_chan_coeffs_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_prog_fir1_single_chan_coeffs_wrapper.ngc \
implementation/system_darkquad29_wvl_prog_fir2_load_chan_wrapper.ngc \
implementation/system_darkquad29_wvl_prog_fir2_single_chan_coeffs_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_prog_fir2_single_chan_coeffs_wrapper.ngc \
implementation/system_darkquad29_wvl_prog_fir3_load_chan_wrapper.ngc \
implementation/system_darkquad29_wvl_prog_fir3_single_chan_coeffs_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_prog_fir3_single_chan_coeffs_wrapper.ngc \
implementation/system_darkquad29_wvl_run_wrapper.ngc \
implementation/system_darkquad29_wvl_sel_ch_wrapper.ngc \
implementation/system_darkquad29_wvl_snp_phs_ss_bram_ramblk_wrapper.ngc \
implementation/system_darkquad29_wvl_snp_phs_ss_bram_wrapper.ngc \
implementation/system_darkquad29_wvl_snp_phs_ss_ctrl_wrapper.ngc \
implementation/system_darkquad29_wvl_snp_phs_ss_status_wrapper.ngc \
implementation/system_darkquad29_wvl_start_cap_wrapper.ngc \
implementation/system_darkquad29_wvl_timekeeper_base_ts_wrapper.ngc \
implementation/system_darkquad29_wvl_timekeeper_sec_now_wrapper.ngc \
implementation/system_darkquad29_wvl_trig_snp_wrapper.ngc \
implementation/system_opb1_wrapper.ngc \
implementation/system_opb2opb_bridge_opb1_wrapper.ngc \
implementation/system_opb2_wrapper.ngc \
implementation/system_opb2opb_bridge_opb2_wrapper.ngc \
implementation/system_opb3_wrapper.ngc \
implementation/system_opb2opb_bridge_opb3_wrapper.ngc \
implementation/system_opb4_wrapper.ngc \
implementation/system_opb2opb_bridge_opb4_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

SDK_EXPORT_DIR = SDK/SDK_Export/hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_DEP = $(SYSTEM_HW_HANDOFF) $(SYSTEM_HW_HANDOFF_BIT)
